\documentclass{article}
\usepackage[margin=1.0in]{geometry} % To set margins
\usepackage{amsmath}  % This allows me to use the align functionality.
                      % If you find yourself trying to replicate
                      % something you found online, ensure you're
                      % loading the necessary packages!
\usepackage{amsfonts} % Math font
\usepackage{fancyvrb}
\usepackage{hyperref} % For including hyperlinks
\usepackage[shortlabels]{enumitem}% For enumerated lists with labels specified
                                  % We had to run tlmgr_install("enumitem") in R
\usepackage{float}    % For telling R where to put a table/figure
\usepackage{natbib}        %For the bibliography
\bibliographystyle{apalike}%For the bibliography

\begin{document}
<<echo=F, message=F, warning=F>>=
library(tidyverse)
library(pwr)
library(VGAM)
@

\begin{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\item A group of researchers is running an experiment over the course of 30 months, 
with a single observation collected at the end of each month. Let $X_1, ..., X_{30}$
denote the observations for each month. From prior studies, the researchers know that
\[X_i \sim f_X(x),\]
but the mean $\mu_X$ is unknown, and they wish to conduct the following test
\begin{align*}
H_0&: \mu_X = 0\\
H_a&: \mu_X > 0.
\end{align*}
At month $k$, they have accumulated data $X_1, ..., X_k$ and they have the 
$t$-statistic
\[T_k = \frac{\bar{X} - 0}{S_k/\sqrt{n}}.\]
The initial plan was to test the hypotheses after all data was collected (at the 
end of month 30), at level $\alpha=0.05$. However, conducting the experiment is 
expensive, so the researchers want to ``peek" at the data at the end of month 20 
to see if they can stop it early. That is, the researchers propose to check 
whether $t_{20}$ provides statistically discernible support for the alternative. 
If it does, they will stop the experiment early and report support for the 
researcher's alternative hypothesis. If it does not, they will continue to month 
30 and test whether $t_{30}$ provides statistically discernible support for the
alternative.

\begin{enumerate}
  \item What values of $t_{20}$ provide statistically discernible support for the
  alternative hypothesis? 
<<message =F, warning =F, size = 'scriptsize'>>=
n =20
(boundary.20 <- qt(1-0.05,df = n-1))

@
  \item What values of $t_{30}$ provide statistically discernible support for the
  alternative hypothesis?
<<message =F, warning =F, size = 'scriptsize'>>=
n =30
(boundary.30 <- qt(1-0.05,df = n-1))

@

  \item Suppose $f_X(x)$ is a Laplace distribution with $a=0$ and $b=4.0$.
  Conduct a simulation study to assess the Type I error rate of this approach.\\
  \textbf{Note:} You can use the \texttt{rlaplace()} function from the \texttt{VGAM}
  package for \texttt{R} \citep{VGAM}.
<<message =F, warning =F, size = 'scriptsize'>>=
R <- 10000
alpha <- 0.05
n<- 30

error.counter <- 0

for(i in 1:R){
  sample <- rlaplace(n, location= 0, scale =4)
  t.test20 <- t.test(sample[1:20], mu = 0)
  t.20 <- t.test20$statistic
  
  t.test.full <- t.test(sample, mu = 0)
  t.30 <- t.test.full$statistic
  
  # reject null or not at month 20? 
  # else check at month 30
  if (t.20 > boundary.20) {
    error.counter <- error.counter + 1
  } else if (t.30 > boundary.30) {
    error.counter <- error.counter + 1
  }
  
}

# estimate type 1 error rate
(t1.error.rate <- error.counter / R)

@
  
  \item \textbf{Optional Challenge:} Can you find a value of $\alpha<0.05$ that yields a 
  Type I error rate of 0.05?
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Question 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \item Perform a simulation study to assess the robustness of the $T$ test. 
  Specifically, generate samples of size $n=15$ from the Beta(10,2), Beta(2,10), 
  and Beta(10,10) distributions and conduct the following hypothesis tests against 
  the actual mean for each case (e.g., $\frac{10}{10+2}$, $\frac{2}{10+2}$, and 
  $\frac{10}{10+10}$). 
<<message =F, warning =F, size = 'scriptsize'>>=
R <- 10000 # trials
alpha <- 0.05 # significance level
n =15 # sample size

real.mean10.2 <- 10/(10+2)
real.mean2.10 <- 2/(10+2)
real.mean10.10 <- 10/(10+10)

means <- c(real.mean10.2, real.mean2.10, real.mean10.10)

# each beta counter will track the left, right, and two tailed tests
error.counter10.2 <- c(0,0,0)
error.counter2.10 <- c(0,0,0)
error.counter10.10 <- c(0,0,0)

for(i in 1:R){
  sample.beta1 <- rbeta(n, 10, 2)
  sample.beta2 <- rbeta(n, 2, 10)
  sample.beta3 <- rbeta(n, 10, 10)
  
  ## Beta(10,2) tests 
  t.left1 <- t.test(sample.beta1, mu= means[1], alternative="less")
  t.right1 <- t.test(sample.beta1, mu= means[1], alternative="greater")
  t.both1 <- t.test(sample.beta1, mu= means[1], alternative="two.sided")
  
  error.counter10.2[1] <- error.counter10.2[1] + (t.left1$p.value < alpha)
  error.counter10.2[2] <- error.counter10.2[2] + (t.right1$p.value < alpha)
  error.counter10.2[3] <- error.counter10.2[3] + (t.both1$p.value < alpha)
  
  ## Beta(2,10) tests 
  t.left2 <- t.test(sample.beta2, mu= means[2], alternative="less")
  t.right2 <- t.test(sample.beta2, mu= means[2], alternative="greater")
  t.both2 <- t.test(sample.beta2, mu= means[2], alternative="two.sided")
  
  error.counter2.10[1] <- error.counter2.10[1] + (t.left2$p.value < alpha)
  error.counter2.10[2] <- error.counter2.10[2] + (t.right2$p.value < alpha)
  error.counter2.10[3] <- error.counter2.10[3] + (t.both2$p.value < alpha)
  
  ## Beta(10,10) tests 
  t.left3 <- t.test(sample.beta3, mu= means[3], alternative="less")
  t.right3 <- t.test(sample.beta3, mu= means[3], alternative="greater")
  t.both3 <- t.test(sample.beta3, mu= means[3], alternative="two.sided")
  
  error.counter10.10[1] <- error.counter10.10[1] + (t.left3$p.value < alpha)
  error.counter10.10[2] <- error.counter10.10[2] + (t.right3$p.value < alpha)
  error.counter10.10[3] <- error.counter10.10[3] + (t.both3$p.value < alpha)
  
  
}

# Compute Type I error rates
type1_error_rate_10_2 <- error.counter10.2 / R
type1_error_rate_2_10 <- error.counter2.10 / R
type1_error_rate_10_10 <- error.counter10.10 / R
@

  \begin{enumerate}
    \item What proportion of the time do we make an error of Type I for a
    left-tailed test? \textbf(Proportions are given in order of $Beta$(10,2), $Beta$(2,10), $Beta$(10,10))
<<echo = F, size = 'scriptsize'>>=
c(type1_error_rate_10_2[1], type1_error_rate_2_10[1],type1_error_rate_10_10[1] )
@

    \item What proportion of the time do we make an error of Type I for a
    right-tailed test?
<<echo = F, size = 'scriptsize'>>=
c(type1_error_rate_10_2[2], type1_error_rate_2_10[2],type1_error_rate_10_10[2] )
@
    
    \item What proportion of the time do we make an error of Type I for a
    two-tailed test?
 <<echo = F, size = 'scriptsize'>>=
c(type1_error_rate_10_2[3], type1_error_rate_2_10[3],type1_error_rate_10_10[3] )
@

   \item How does skewness of the underlying population distribution effect
    Type I error across the test types?
    \textbf(Answer: The t-test assumes a relatively symmetrical distribution for data, so skewness could inflate or deflate a testing error. As we can see from this example, the direction of the skewness would decrease the Type I error in that direction and increase the error in the other direction. Using the two tailed test as the normal, we can compare it against the skewness and Type I errors of the other graphs. For example, the $Beta$(10,2) distribution is skewed left, and it produced a lower Type I error to the left but a higher proportion of it to the right. These error proportions are flipped for the $Beta$(2,10) distribution which is skewed right. )
    
  \end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End Document
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\end{enumerate}
\bibliography{bibliography}
\end{document}
